app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("src.home.urls")),
    path("accounts/", include("src.accounts.urls")),
    path("organization/", include("src.organization.routes.urls")),
    path("game/", include("src.game.routes.urls")),
    path("admin/", admin.site.urls),
]

src/accounts/urls.py
from django.urls import path
from src.accounts.views import Login, Logout, UserRegisterView, UserRedirectView

app_name = "accounts"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", UserRegisterView.as_view(), name="registration"),
    path("redirect/", UserRedirectView.as_view(), name="redirect"),
]

src/home/urls.py
from django.urls import path
from src.home.views import IndexView

app_name = "home"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
]

src/core/models/base_model.py
from typing import Any
from django.db import models
from django.utils import timezone

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    def delete(self, using: Any = ..., keep_parents: bool = ..., soft: bool = True) -> tuple[int, dict[str, int]]:
        if soft:
            self.deleted_at = timezone.now()
            self.save()
            return (1, {})
        
        return super().delete(using, keep_parents)

    class Meta:
        abstract = True

src/game/routes/joint_urls.py
from django.urls import path
from src.game.views.joint import JointListView, JointCreateView, JointUpdateView, JointDetailsView, JointDeleteView

app_name = "joint"

urlpatterns = [
    path("", JointListView.as_view(), name="list"),
    path("registration/", JointCreateView.as_view(), name="registration"),
    path("update/<int:pk>/", JointUpdateView.as_view(), name="update"),
    path("details/<int:pk>/", JointDetailsView.as_view(), name="details"),
    path("delete/<int:pk>/", JointDeleteView.as_view(), name="delete"),
]

src/game/routes/word_urls.py
from django.urls import path
from src.game.views.words import WordListView, WordCreateView, WordUpdateView, WordDetailsView, WordDeleteView

app_name = "word"

urlpatterns = [
    path("", WordListView.as_view(), name="list"),
    path("registration/", WordCreateView.as_view(), name="registration"),
    path("update/<int:pk>/", WordUpdateView.as_view(), name="update"),
    path("details/<int:pk>/", WordDetailsView.as_view(), name="details"),
    path("delete/<int:pk>/", WordDeleteView.as_view(), name="delete"),
]

src/core/templates/components/base_form.html
<div>
    <h1 class="mb-2">{{ form_title }}</h1>
    <form id="baseForm" method="get">
        {% csrf_token %}
        {% for field in form %}
            <div class="flex mb-2">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <input type="submit" onclick="submitAsPost()" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 border border-gray-300 rounded" value="{{ submit_button_text }}">
    </form>
    {% if form.errors %}
        <div class="errorlist">
            {% for field, errors in form.errors.items %}
                <strong>{{ field.label_tag }}:</strong> {{ errors }}
            {% endfor %}
        </div>
    {% endif %}
</div>

<script>
    function submitAsPost() {
        var form = document.getElementById("baseForm");
        form.method = "post";
      }
</script>

src/core/templates/components/base_object_delete.html
<div>
    <h1 class="mb-2">{{ form_title }}</h1>
    <form method="post">
        {% csrf_token %}
        <p class="mb-2">Tem certeza que deseja deletar {{ object_type }} '{{ object }}' ?</p>
        <input type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 border border-gray-300 rounded" value="Deletar">
    </form>
</div>

src/core/templates/components/base_object_details.html
{% load get_attribute %}
<div>
    <h1 class="mb-2">Detalhes do registro {{ model_description }}: '{{ object }}'</h1>
    <div>
        {% for field, label in field_names.items %}
            <div class="flex mb-2">
                {{ label }}: {{ object|get_attribute:field }}
            </div>
        {% endfor %}
    </div>

    <td scope="row" class="px-4 py-4 whitespace-nowrap">
        {% for action, icon in control_buttons.items %}
            {% if 'list' in action %}
                <a href="{% url action %}" class="ml-2">
                    <i class="{{ icon }}"></i>
                </a>
            {% else %}
                <a href="{% url action object.id %}" class="ml-2">
                    <i class="{{ icon }}"></i>
                </a>
            {% endif %}
        {% endfor %}
    </td>
</div>

src/core/templates/components/navbar_authenticated.html
<div class="flex">
    <div class="w-1/5 flex gap-2 justify-start">
        <a href="{% url 'home:index' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            <i class="fa-solid fa-house"></i>
        </a>
    </div>
    <div class="w-3/5 flex gap-2 justify-center">
        <a href="{% url 'word:registration' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            criar palavra
        </a>
        
        <a href="{% url 'word:list' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            lista de palavras
        </a>
        <a href="{% url 'joint:registration' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            criar conjunto
        </a>
        
        <a href="{% url 'joint:list' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            lista de conjuntos
        </a>

        <a href="{% url 'exercise:registration' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            criar exercício
        </a>

        <a href="{% url 'organization:registration' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            registrar organização
        </a>
        
        <a href="{% url 'organization:list' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            lista de organizações
        </a>
        
    </div>
    <div class="w-1/5 flex gap-2 justify-end">
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <button class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
                <i class="fa-solid fa-right-from-bracket"></i>
            </button>
        </form>
    </div>
</div>

src/core/templates/components/navbar_not_authenticated.html
<div class="flex">
    <div class="w-1/3 flex gap-2 justify-start">
        <a href="{% url 'home:index' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            <i class="fa-solid fa-house"></i>
        </a>
    </div>
    <div class="w-1/3 flex gap-2 justify-center">
    </div>
    <div class="w-1/3 flex gap-2 justify-end">
        <a href="{% url 'accounts:login' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            <i class="fa-solid fa-right-to-bracket"></i>
        </a>
        <a href="{% url 'accounts:registration' %}" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
            <i class="fa-solid fa-user-plus"></i>
        </a> 
    </div>
</div>

src/core/templates/components/table_with_pagination.html
{% load get_attribute %}
{% load sort_by %}
<div class="m-5 rounded-lg">
    <!-- pagination search bar and table title -->
    <div class="grid grid-cols-3 px-6 py-4 font-bold">
        <div></div>
        <div class="text-center text-3xl">
            <p>{{ title }}</p>
        </div>
        <form method="GET" class="flex items-center px-10 gap-1">
            <p>Buscar:</p>
            <input type="text" value="{{ search }}" name="search" class="w-full bg-inherit border-b-2 border-black focus:outline-none focus:border-teal-800 p-2 cursor-pointer">
            <button type="submit" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
            <a href="" class="bg-[#8696a0] hover:bg-teal-800 text-white p-2 rounded mt-3 cursor-pointer">
                <i class="fa-solid fa-delete-left"></i>
            </a> 
        </form>
    </div>

    <!-- table itself -->
    <table class="w-full text-sm text-left rtl:text-right text-gray-500">
        <thead class="text-xs font-bold uppercase">
            <tr class="border-b border-black">
                {% for header in headers %}
                    <th scope="col" class="px-6 py-3">
                        <a href="{% sort_by forloop.counter0 %}">{{ header }}</a>
                    </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr class="border-b border-black">
                    {% for field in accessors %}
                        {% if field != 'action' %}
                            <td scope="row" class="px-6 py-4 whitespace-nowrap">{{ object|get_attribute:field }}</td>
                        {% endif %}
                    {% endfor %}
                    
                    <td scope="row" class="px-4 py-4 whitespace-nowrap">
                        {% for action, icon in actions.items %}
                            <a href="{% url action object.id %}" class="ml-2">
                                <i class="{{ icon }}"></i>
                            </a>
                        {% endfor %}
                    </td>

                </tr>
            {% empty %}
                <tr class="border-b border-black">
                    <td scope="row" class="px-6 py-4 whitespace-nowrap text-center" colspan="{{ headers|length }}">Nenhum registro encontrado</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- pagination -->
    <div class="pagination items-center justify-center text-md font-medium flex mx-auto">
        <span class="step-links flex items-center justify-center w-1/4">
            {% if pagination_controls.has_previous %}
                <a 
                    class="flex items-center justify-center px-1 h-8 font-medium rounded hover:bg-teal-800" 
                    href="?page=1{% if search %}&search={{ search }}{% endif %}"
                >
                    <i class="fa-solid fa-backward"></i>
                </a>

                <a 
                    class="flex items-center justify-center px-1 h-8 font-medium rounded hover:bg-teal-800" 
                    href="?page={{ pagination_controls.previous_page_number }}{% if search %}&search={{ search }}{% endif %}"
                >
                    <i class="fa-solid fa-caret-left"></i>
                </a>

            {% endif %}
            <span 
                class="current "
            >
                Pagina <span class="font-semibold">{{ pagination_controls.number }}</span> 
                de <span class="font-semibold">{{ pagination_controls.paginator.num_pages }}</span>.
            </span>

            {% if pagination_controls.has_next %}
                <a 
                    class="flex items-center justify-center px-1 h-8 font-medium rounded hover:bg-teal-800" 
                    href="?page={{ pagination_controls.next_page_number }}{% if search %}&search={{ search }}{% endif %}"
                >
                    <i class="fa-solid fa-caret-right"></i>
                </a>

                <a 
                    class="flex items-center justify-center px-1 h-8 font-medium rounded hover:bg-teal-800" 
                    href="?page={{ pagination_controls.paginator.num_pages }}{% if search %}&search={{ search }}{% endif %}"
                >
                    <i class="fa-solid fa-forward"></i>
                </a>
            {% endif %}
        </span>
    </div>
</div>